### ISSUE TITLE
contact | Shanya的博客

### ISSUE THREAD

**Issue by Shanyaliux** [Shanyaliux/comment#31]
https://www.shanya.world/contact/ 

 分享生活,分享知识

**Comment by wanzhr** [comment]
大佬牛批，小弟来摩拜下

**Comment by wanzhr** [comment]
我想请问一下，你的这个个人博客是用的什么搭建的，我也想整一个

**Comment by Shanyaliux** [comment]
> @wanzhr
> 我想请问一下，你的这个个人博客是用的什么搭建的，我也想整一个

感谢关注！ 这个个人博客用的是 `hexo` 框架 配合`GithubPage` 做的， 博客中有相关文章讲解制作过程

**Comment by wanzhr** [comment]
看到了，谢谢分享！
