### ISSUE TITLE
PicGo 配合 Gitee 实现个人博客的高速稳定图床 | Shanya的博客

### ISSUE THREAD

**Issue by Shanyaliux** [Shanyaliux/comment#36]
https://www.shanya.world/archives/c77f2ba5.html 

 前言之前用的图床是GIthub上的，使用了 jsDelivr 进行加速，详细请见文章    VSCode + Github + Picgo + jsDelivr 搭建稳定快速高效图床   但是这样的作法有时候会出点小bug，需要重复上传才行。现发现可以使用Gitee进行图床的搭建，所以水篇文章记录一下（^_^）。 安装相关软件及扩展 安装Picgo客户端 下载地址  在Picgo里面安装Gitee

**Comment by skyshenma** [comment]
大佬，我也这样弄的图床，但是有个问题。不知道为啥，博客在微信里面直接打开的话，显示不出图片，但是用浏览器又可以显示，这点很是尴尬。

**Comment by Shanyaliux** [comment]
> @skyshenma
> 大佬，我也这样弄的图床，但是有个问题。不知道为啥，博客在微信里面直接打开的话，显示不出图片，但是用浏览器又可以显示，这点很是尴尬。

应该不是图床的问题，我用微信内置浏览器连博客网页都打不开
